version: 2

jobs:

  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Combat preparation
          command: docker-compose up -d default
      - run:
          name: Build the application
          command: docker-compose exec default yarn build:app
      - run:
          name: Build cloud functions
          command: docker-compose exec default yarn build:api

  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Combat preparation
          command: |
            docker-compose up -d default
            docker-compose exec default yarn build:app
            docker-compose exec default yarn build:api
            docker-compose exec default yarn firebase use development --token ${FIREBASE_TOKEN}
            docker-compose exec -d default yarn firebase serve --only hosting -p 8000 --token ${FIREBASE_TOKEN}
            # docker-compose exec -d default yarn firebase serve --only functions -p 5000 --token ${FIREBASE_TOKEN}
      - run:
          name: Check the code
          command: |
            docker-compose exec default yarn lint:js
            docker-compose exec default yarn lint:css
      - run:
          name: Test the application
          command: |
            docker-compose exec default yarn test:app
            docker-compose exec default yarn codecov --token=${CODECOV_TOKEN}
      - run:
          name: Test cloud functions
          command: |
            docker-compose exec default yarn test:api
            docker-compose exec default yarn codecov --token=${CODECOV_TOKEN}
      - run:
          name: End-to-end UI tests
          command: |
            docker-compose exec default sh -c "sleep 10"
            docker-compose exec default yarn e2e:app
      - run:
          name: End-to-end HTTP tests
          command: |
            # docker-compose exec default sh -c "sleep 10"
            # docker-compose exec default yarn e2e:api

  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy to development
          command: |
            if [[ "${CIRCLE_BRANCH}" == "develop" ]]; then
              # docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}
              docker-compose up -d dev
              docker-compose exec dev yarn firebase use development --token ${FIREBASE_TOKEN}
              docker-compose exec dev yarn firebase deploy --token ${FIREBASE_TOKEN}
            fi
      - run:
          name: Deploy to production
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              # docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}
              docker-compose up -d prod
              docker-compose exec prod yarn firebase use production --token ${FIREBASE_TOKEN}
              docker-compose exec prod yarn firebase deploy --token ${FIREBASE_TOKEN}
            fi

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
